### ISSUE TITLE
中文网站的更新频率

### ISSUE THREAD

**Issue by YoungChiyu** [johnzeng/rocksdb-doc-cn#20]
请问在PR中校对的一些修改和新翻译的内容大概是一个怎样的频率更新到中文网站上呢？

**Comment by johnzeng** [comment]
最初他们是跟我说设置了自动拉取。我好久没关注了。那个网站其实也是民间组织维护的，如果你发现他没有更新，我去找下维护人，问下看看

**Comment by YoungChiyu** [comment]
看着好像是没有同步更新

**Comment by johnzeng** [comment]
我给维护人说了这个事情。但是不确定他会不会去更新。。。你可以再关注下。
